#!/usr/bin/env bash

old_pwd="$PWD"
cd $(dirname $0)
rm -r -f output
mkdir -p output

if [ $1 == 'install' ]; then
    python3 src/metric_utility_functions/localclone_install.py
elif [ $1 == 'build' ]; then 
    cargo build;
elif [ $1 == 'clean' ]; then 
    rm log_file.log; rm -r -f target; rm -r -f output
elif [ $1 == 'tempclean' ]; then 
    rm testfile.txt && cd output && rm *.txt && cd ../log && rm *.txt;
elif [ $1 == 'test' ]; then
    export $(cat .env | xargs)
    python3 -m pytest #-s
    cargo test
elif [ $1 == 'server' ]; then
    export $(cat .env | xargs)
    python3 -m src.APIs.__init__
else
    export $(cat .env | xargs)
    cargo run "$@"
fi

cd $old_pwd