/*
 * ECE 461 - Spring 2023 - Project 2
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * OpenAPI spec version: 2.0.0
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Ece461Spring2023Project2);
  }
}(this, function(expect, Ece461Spring2023Project2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PackageHistoryEntry', function() {
      beforeEach(function() {
        instance = new Ece461Spring2023Project2.PackageHistoryEntry();
      });

      it('should create an instance of PackageHistoryEntry', function() {
        // TODO: update the code to test PackageHistoryEntry
        expect(instance).to.be.a(Ece461Spring2023Project2.PackageHistoryEntry);
      });

      it('should have the property user (base name: "User")', function() {
        // TODO: update the code to test the property user
        expect(instance).to.have.property('user');
        // expect(instance.user).to.be(expectedValueLiteral);
      });

      it('should have the property _date (base name: "Date")', function() {
        // TODO: update the code to test the property _date
        expect(instance).to.have.property('_date');
        // expect(instance._date).to.be(expectedValueLiteral);
      });

      it('should have the property packageMetadata (base name: "PackageMetadata")', function() {
        // TODO: update the code to test the property packageMetadata
        expect(instance).to.have.property('packageMetadata');
        // expect(instance.packageMetadata).to.be(expectedValueLiteral);
      });

      it('should have the property action (base name: "Action")', function() {
        // TODO: update the code to test the property action
        expect(instance).to.have.property('action');
        // expect(instance.action).to.be(expectedValueLiteral);
      });

    });
  });

}));
