/*
 * ECE 461 - Spring 2023 - Project 2
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * OpenAPI spec version: 2.0.0
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PackageName} from './PackageName';
import {SemverRange} from './SemverRange';

/**
 * The PackageQuery model module.
 * @module model/PackageQuery
 * @version 2.0.0
 */
export class PackageQuery {
  /**
   * Constructs a new <code>PackageQuery</code>.
   * @alias module:model/PackageQuery
   * @class
   * @param name {module:model/PackageName} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>PackageQuery</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PackageQuery} obj Optional instance to populate.
   * @return {module:model/PackageQuery} The populated <code>PackageQuery</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PackageQuery();
      if (data.hasOwnProperty('Version'))
        obj.version = SemverRange.constructFromObject(data['Version']);
      if (data.hasOwnProperty('Name'))
        obj.name = PackageName.constructFromObject(data['Name']);
    }
    return obj;
  }
}

/**
 * @member {module:model/SemverRange} version
 */
PackageQuery.prototype.version = undefined;

/**
 * @member {module:model/PackageName} name
 */
PackageQuery.prototype.name = undefined;

