/*
 * ECE 461 - Spring 2023 - Project 2
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * OpenAPI spec version: 2.0.0
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PackageData model module.
 * @module model/PackageData
 * @version 2.0.0
 */
export class PackageData {
  /**
   * Constructs a new <code>PackageData</code>.
   * This is a \&quot;union\&quot; type. - On package upload, either Content or URL should be set. - On package update, exactly one field should be set. - On download, the Content field should be set.
   * @alias module:model/PackageData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PackageData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PackageData} obj Optional instance to populate.
   * @return {module:model/PackageData} The populated <code>PackageData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PackageData();
      if (data.hasOwnProperty('Content'))
        obj.content = ApiClient.convertToType(data['Content'], 'String');
      if (data.hasOwnProperty('URL'))
        obj.URL = ApiClient.convertToType(data['URL'], 'String');
      if (data.hasOwnProperty('JSProgram'))
        obj.jSProgram = ApiClient.convertToType(data['JSProgram'], 'String');
    }
    return obj;
  }
}

/**
 * Package contents. This is the zip file uploaded by the user. (Encoded as text using a Base64 encoding).  This will be a zipped version of an npm package's GitHub repository, minus the \".git/\" directory.\" It will, for example, include the \"package.json\" file that can be used to retrieve the project homepage.  See https://docs.npmjs.com/cli/v7/configuring-npm/package-json#homepage.
 * @member {String} content
 */
PackageData.prototype.content = undefined;

/**
 * Package URL (for use in public ingest).
 * @member {String} URL
 */
PackageData.prototype.URL = undefined;

/**
 * A JavaScript program (for use with sensitive modules).
 * @member {String} jSProgram
 */
PackageData.prototype.jSProgram = undefined;

