/*
 * ECE 461 - Spring 2023 - Project 2
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * OpenAPI spec version: 2.0.0
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PackageMetadata} from './PackageMetadata';
import {User} from './User';

/**
 * The PackageHistoryEntry model module.
 * @module model/PackageHistoryEntry
 * @version 2.0.0
 */
export class PackageHistoryEntry {
  /**
   * Constructs a new <code>PackageHistoryEntry</code>.
   * One entry of the history of this package.
   * @alias module:model/PackageHistoryEntry
   * @class
   * @param user {module:model/User} 
   * @param _date {Date} Date of activity.
   * @param packageMetadata {module:model/PackageMetadata} 
   * @param action {module:model/PackageHistoryEntry.ActionEnum} 
   */
  constructor(user, _date, packageMetadata, action) {
    this.user = user;
    this._date = _date;
    this.packageMetadata = packageMetadata;
    this.action = action;
  }

  /**
   * Constructs a <code>PackageHistoryEntry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PackageHistoryEntry} obj Optional instance to populate.
   * @return {module:model/PackageHistoryEntry} The populated <code>PackageHistoryEntry</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PackageHistoryEntry();
      if (data.hasOwnProperty('User'))
        obj.user = User.constructFromObject(data['User']);
      if (data.hasOwnProperty('Date'))
        obj._date = ApiClient.convertToType(data['Date'], 'Date');
      if (data.hasOwnProperty('PackageMetadata'))
        obj.packageMetadata = PackageMetadata.constructFromObject(data['PackageMetadata']);
      if (data.hasOwnProperty('Action'))
        obj.action = ApiClient.convertToType(data['Action'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/User} user
 */
PackageHistoryEntry.prototype.user = undefined;

/**
 * Date of activity.
 * @member {Date} _date
 */
PackageHistoryEntry.prototype._date = undefined;

/**
 * @member {module:model/PackageMetadata} packageMetadata
 */
PackageHistoryEntry.prototype.packageMetadata = undefined;

/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
PackageHistoryEntry.ActionEnum = {
  /**
   * value: "CREATE"
   * @const
   */
  CREATE: "CREATE",

  /**
   * value: "UPDATE"
   * @const
   */
  UPDATE: "UPDATE",

  /**
   * value: "DOWNLOAD"
   * @const
   */
  DOWNLOAD: "DOWNLOAD",

  /**
   * value: "RATE"
   * @const
   */
  RATE: "RATE"
};
/**
 * @member {module:model/PackageHistoryEntry.ActionEnum} action
 */
PackageHistoryEntry.prototype.action = undefined;

