/*
 * ECE 461 - Spring 2023 - Project 2
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * OpenAPI spec version: 2.0.0
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserAuthenticationInfo model module.
 * @module model/UserAuthenticationInfo
 * @version 2.0.0
 */
export class UserAuthenticationInfo {
  /**
   * Constructs a new <code>UserAuthenticationInfo</code>.
   * Authentication info for a user
   * @alias module:model/UserAuthenticationInfo
   * @class
   * @param password {String} Password for a user. Per the spec, this should be a \"strong\" password.
   */
  constructor(password) {
    this.password = password;
  }

  /**
   * Constructs a <code>UserAuthenticationInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserAuthenticationInfo} obj Optional instance to populate.
   * @return {module:model/UserAuthenticationInfo} The populated <code>UserAuthenticationInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserAuthenticationInfo();
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * Password for a user. Per the spec, this should be a \"strong\" password.
 * @member {String} password
 */
UserAuthenticationInfo.prototype.password = undefined;

