/*
 * ECE 461 - Spring 2023 - Project 2
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * OpenAPI spec version: 2.0.0
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {AuthenticationRequest} from './model/AuthenticationRequest';
import {AuthenticationToken} from './model/AuthenticationToken';
import {EnumerateOffset} from './model/EnumerateOffset';
import {Error} from './model/Error';
import {ModelPackage} from './model/ModelPackage';
import {PackageData} from './model/PackageData';
import {PackageHistoryEntry} from './model/PackageHistoryEntry';
import {PackageID} from './model/PackageID';
import {PackageMetadata} from './model/PackageMetadata';
import {PackageName} from './model/PackageName';
import {PackageQuery} from './model/PackageQuery';
import {PackageRating} from './model/PackageRating';
import {PackageRegEx} from './model/PackageRegEx';
import {SemverRange} from './model/SemverRange';
import {User} from './model/User';
import {UserAuthenticationInfo} from './model/UserAuthenticationInfo';
import {DefaultApi} from './api/DefaultApi';

/**
* API_for_ECE_461Spring_2023Project_2_A_Trustworthy_Module_Registry.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Ece461Spring2023Project2 = require('index'); // See note below*.
* var xxxSvc = new Ece461Spring2023Project2.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Ece461Spring2023Project2.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Ece461Spring2023Project2.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Ece461Spring2023Project2.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthenticationRequest model constructor.
     * @property {module:model/AuthenticationRequest}
     */
    AuthenticationRequest,

    /**
     * The AuthenticationToken model constructor.
     * @property {module:model/AuthenticationToken}
     */
    AuthenticationToken,

    /**
     * The EnumerateOffset model constructor.
     * @property {module:model/EnumerateOffset}
     */
    EnumerateOffset,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The ModelPackage model constructor.
     * @property {module:model/ModelPackage}
     */
    ModelPackage,

    /**
     * The PackageData model constructor.
     * @property {module:model/PackageData}
     */
    PackageData,

    /**
     * The PackageHistoryEntry model constructor.
     * @property {module:model/PackageHistoryEntry}
     */
    PackageHistoryEntry,

    /**
     * The PackageID model constructor.
     * @property {module:model/PackageID}
     */
    PackageID,

    /**
     * The PackageMetadata model constructor.
     * @property {module:model/PackageMetadata}
     */
    PackageMetadata,

    /**
     * The PackageName model constructor.
     * @property {module:model/PackageName}
     */
    PackageName,

    /**
     * The PackageQuery model constructor.
     * @property {module:model/PackageQuery}
     */
    PackageQuery,

    /**
     * The PackageRating model constructor.
     * @property {module:model/PackageRating}
     */
    PackageRating,

    /**
     * The PackageRegEx model constructor.
     * @property {module:model/PackageRegEx}
     */
    PackageRegEx,

    /**
     * The SemverRange model constructor.
     * @property {module:model/SemverRange}
     */
    SemverRange,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserAuthenticationInfo model constructor.
     * @property {module:model/UserAuthenticationInfo}
     */
    UserAuthenticationInfo,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
